### ISSUE TITLE
Where are the environment variables generated and accessed?

### ISSUE THREAD

**Issue by tutnes** [Dynatrace/Dynatrace-AppMon-Generic-Execution-Plugin#1]
Hi, the environment variables ${VARIABLE_NAME}, where are they accessed, and is there a class or something that I can look at for this?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Tarjei,

What environment variables do you mean specifically? AFAIK there are no environment variables getting passed to the child process.

thanks,
Reinhard

**Comment by tutnes** [comment]
I am thinking about these variables (see link)
https://community.dynatrace.com/community/download/attachments/120128619/BodyHeaderExample.html?version=4&modificationDate=1481036308717&api=v2

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Ok, now I understand.
The classes you are looking for are just available as jar file within the lib-folder.
[actionhelper_5.5.4.jar](https://github.com/Dynatrace/Dynatrace-Generic-Execution-Plugin/blob/master/lib/actionhelper_5.5.4.jar?raw=true) contains the classes SubstitutorFields and ActionHelper.

I don't have access to the source code of that helper library as of this moment, but managed to verify that this is what you're looking for by decompiling them.

Are there any issues with these variables?

**Comment by tutnes** [comment]
No, but then I know where I should access them. Thank you very much.
